#!/bin/bash
git fetch
git status
echo -e "\033[1;35mPull?\033[0m"
while true; do
  read -p "" yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Human says yes or no?";;
    esac
done
git pull
